/**
 * One entry per fixture in tests/fixtures/rules/invalid/: the path substring
 * validate.spec.ts expects to see among the reported issues.
 */
export const INVALID_FIXTURES: ReadonlyArray<{ name: string; expectedPathSubstring: string }> = [
  { name: 'not-an-object', expectedPathSubstring: '' },
  { name: 'missing-version', expectedPathSubstring: '/version' },
  { name: 'wrong-version', expectedPathSubstring: '/version' },
  { name: 'empty-id', expectedPathSubstring: '/id' },
  { name: 'missing-name', expectedPathSubstring: '/name' },
  { name: 'bad-description-type', expectedPathSubstring: '/description' },
  { name: 'bad-author-type', expectedPathSubstring: '/author' },
  { name: 'bad-symmetry', expectedPathSubstring: '/symmetry' },
  { name: 'empty-states', expectedPathSubstring: '/states' },
  { name: 'states-not-array', expectedPathSubstring: '/states' },
  { name: 'state-missing-id', expectedPathSubstring: '/states/0/id' },
  { name: 'state-negative-id', expectedPathSubstring: '/states/0/id' },
  { name: 'state-missing-name', expectedPathSubstring: '/states/0/name' },
  { name: 'state-bad-kind', expectedPathSubstring: '/states/0/kind' },
  { name: 'state-missing-countsAsAlive', expectedPathSubstring: '/states/0/countsAsAlive' },
  { name: 'states-non-contiguous', expectedPathSubstring: '/states' },
  { name: 'states-no-dead', expectedPathSubstring: '/states' },
  { name: 'states-two-dead', expectedPathSubstring: '/states' },
  { name: 'dead-state-wrong-id', expectedPathSubstring: '/states' },
  { name: 'bad-boundary', expectedPathSubstring: '/boundary' },
  { name: 'neighborhood-missing-kind', expectedPathSubstring: '/neighborhood' },
  { name: 'neighborhood-bad-kind', expectedPathSubstring: '/neighborhood' },
  { name: 'moore-bad-radius', expectedPathSubstring: '/neighborhood/radius' },
  { name: 'vonneumann-negative-radius', expectedPathSubstring: '/neighborhood/radius' },
  { name: 'custom-offsets-not-array', expectedPathSubstring: '/neighborhood/offsets' },
  { name: 'custom-offsets-with-zero-zero', expectedPathSubstring: '/neighborhood/offsets' },
  { name: 'custom-offsets-exceed-cap', expectedPathSubstring: '/neighborhood/offsets' },
  { name: 'transition-missing-kind', expectedPathSubstring: '/transition' },
  { name: 'transition-bad-kind', expectedPathSubstring: '/transition' },
  { name: 'totalistic-born-out-of-range', expectedPathSubstring: '/transition/born/0' },
  { name: 'totalistic-survive-not-array', expectedPathSubstring: '/transition/survive' },
  { name: 'totalistic-bad-decayStates', expectedPathSubstring: '/transition/decayStates' },
  { name: 'generations-states-too-low', expectedPathSubstring: '/transition/states' },
  { name: 'stateTable-bad-radix', expectedPathSubstring: '/transition/radix' },
  { name: 'stateTable-radix-mismatch', expectedPathSubstring: '/transition/radix' },
  { name: 'stateTable-table-wrong-length', expectedPathSubstring: '/transition/table' },
  { name: 'weighted-weights-wrong-length', expectedPathSubstring: '/transition/weights' },
  { name: 'weighted-thresholds-empty', expectedPathSubstring: '/transition/thresholds' },
  { name: 'weighted-threshold-min-gt-max', expectedPathSubstring: '/transition/thresholds/0' },
  { name: 'weighted-threshold-bad-toState', expectedPathSubstring: '/transition/thresholds/0/toState' },
  { name: 'turmite-empty-states', expectedPathSubstring: '/transition/states' },
  { name: 'turmite-bad-turn', expectedPathSubstring: '/transition/states/0/turn' },
  { name: 'turmite-bad-onCellState', expectedPathSubstring: '/transition/states/0/onCellState' },
];
